spring.application.name=fileService
server.port=8067

# database config
spring.datasource.url=jdbc:mysql://1Panel-mysql-LB97:3306/fileservice?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=fileservice110
spring.datasource.password=QMGQbxcF3dNhfQWX
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.drop-first=false

#
file.upload-dir=./uploads
file.max-storage-size=1073741824
file.download-url-prefix=http://fileservice.docn.net/download/

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

spring.web.error.include-message=never
spring.web.error.include-stacktrace=never
spring.web.error.include-exception=false

logging.level.liquibase=debug
